server {
    listen 80;
    server_name funky.xyz;

    # Certbot HTTP-01 challenge handshake entry location
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect all general web hits to HTTPS secure layer
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name funky.xyz;

    ssl_certificate /etc/letsencrypt/live/funcky.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/funcky.xyz/privkey.pem;

    location / {
        # 💡 Points directly to our service container name inside docker mesh
        proxy_pass http://online-ui:3000; 

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
