apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: ecommerce-app

  template:
    metadata:
      labels:
        app: ecommerce-app

    spec:
      containers:
      - name: ecommerce-app

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: {{ .Values.containerPort }}
