apiVersion: apps/v1
kind: Deployment
metadata:
  name: hmis-mf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hmis-mf
  template:
    metadata:
      labels:
        app: hmis-mf
    spec:
      containers:
      - name: hmis-mf
        image: hmis-mf-nginx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
