apiVersion: v1
kind: Service
metadata:
  name: hmis-mf-service
spec:
  selector:
    app: hmis-mf
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
#      nodePort: 30001
