version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:18.17.0
    environment:
      APP_DIR: react-app
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "SHA256:nvBo8bI+QsWnA9X51EFwxDMrbLDhVU1qtSZGf7Cd9aE"

      - run:
          name: Ensure rsync is installed and copy project to EC2
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
              if ! command -v rsync > /dev/null; then
                if command -v apt > /dev/null; then
                  sudo apt update && sudo apt install rsync -y
                elif command -v yum > /dev/null; then
                  sudo yum install rsync -y
                fi
              fi
            EOF

            rsync -az -e "ssh -o StrictHostKeyChecking=no" ./ $EC2_USER@$EC2_HOST:/home/$EC2_USER/$APP_DIR

      - run:
          name: Build and serve React app on EC2
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
              cd /home/$EC2_USER/$APP_DIR

              # Install dependencies and build
              npm install
              npm run build

              # Install serve globally if not already installed
              if ! command -v serve > /dev/null; then
                npm install -g serve
              fi

              # Kill old process running on port 3000
              fuser -k 3000/tcp || true

              # Start serve in background
              nohup serve -s
