version: 2.1

jobs:
  deploy:
    machine: true
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "SHA256:your-ssh-fingerprint"

      - run: 
          name: Make and Run Deployment Script
          command: |
             chmod +x deploy.sh
             ./deploy.sh

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - deploy


