version: 2.1
environment:
      REPO_URL: https://github.com/Prasannaramesh13/online-shopping-app.git
      APP_DIR: online-shopping-app
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "SHA256:nvBo8bI+QsWnA9X51EFwxDMrbLDhVU1qtSZGf7Cd9aE"  # Replace with your actual fingerprint

      - run:
          name: SSH into EC2 and deploy React app
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST \<< 'EOF'
              # Install required tools
              sudo apt update
              sudo apt install -y git curl psmisc

              # Install Node.js (v18)
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt install -y nodejs

              # Go to home directory
              cd /home/$EC2_USER

              # Remove old repo if it exists (optional)
              rm -rf $APP_DIR

              # Clone the repo
              git clone $REPO_URL $APP_DIR
              cd $APP_DIR

              # Install app dependencies and build
              npm install
              npm run build

              # Install 'serve' to serve the build folder
              sudo npm install -g serve

              # Kill any process already using port 3000
              fuser -k 3000/tcp || true

              # Serve the React app on port 3000 (access via EC2_IP:3000)
              nohup serve -s build -l tcp://0.0.0.0:3000 > /tmp/serve.log 2>&1 &
            EOF

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy



