version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:18.17.0
    environment:
      APP_DIR: react-app
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "SHA256:nvBo8bI+QsWnA9X51EFwxDMrbLDhVU1qtSZGf7Cd9aE"

      - run:
          name: Build and serve React app on EC2
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST \<< 'EOF'
              mkdir -p /home/$EC2_USER/$APP_DIR
              cd /home/$EC2_USER/$APP_DIR
              sudo apt update && sudo apt install git -y
              git clone https://github.com/Prasannaramesh13/online-shopping-app.git
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt install -y nodejs
              # Install dependencies and build
              npm install
              npm run build

              # Install serve globally if not already installed
              if ! command -v serve > /dev/null; then
                npm install -g serve
              fi

              # Kill old process running on port 3000
              fuser -k 3000/tcp || true

              # Start serve in background
              nohup serve -s build -l 3000 > serve.log 2>&1 &
            EOF

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
