version: 2.1

jobs:
  deploy:
    machine: true  # Use a full VM instead of Docker container
    environment:
      REPO_URL: https://github.com/Prasannaramesh13/online-shopping-app.git
      APP_DIR: online-shopping-app
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "SHA256:nvBo8bI+QsWnA9X51EFwxDMrbLDhVU1qtSZGf7Cd9aE"  # Replace with your actual SSH fingerprint

      - run:
          name: SSH into EC2 and deploy React app
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
              # Update system and install required tools
              sudo apt update
              sudo apt install -y git curl psmisc

              # Install Node.js 18
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt install -y nodejs

              # Go to home directory
              cd /home/$EC2_USER

              # Remove existing app directory if it exists
              rm -rf $APP_DIR

              # Clone the GitHub repo
              git clone $REPO_URL $APP_DIR
              cd $APP_DIR

              # Install npm dependencies and build the React app
              npm install
              npm run build

              # Install serve globally if not installed
              if ! command -v serve > /dev/null; then
                sudo npm install -g serve
              fi

              # Kill any existing app running on port 3000
              fuser -k 3000/tcp || true

              # Serve the React app in the background on port 3000
              nohup serve -s build -l tcp://0.0.0.0:3000 > /tmp/serve.log 2>&1 &
            EOF

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy




