version: 2.1

jobs:
  deploy:
    machine: true
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "SHA256:your-ssh-fingerprint"

      - run:
          name: Make build.sh Executable
          command: chmod +x deploy.sh

      - run:
          name: Run Deployment Script
          command: ./deploy.sh

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - deploy


