version: 2.1

jobs:
  deploy:
    machine: true
    environment:
      APP_DIR: online-shopping-app
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "SHA256:nvBo8bI+QsWnA9X51EFwxDMrbLDhVU1qtSZGf7Cd9aE"

      - run:
          name: SSH into EC2 and deploy React app
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST \<< 'EOF'
              # Variables inside the EC2 instance
              APP_DIR=online-shopping-app
              REPO_URL=https://github.com/Prasannaramesh13/online-shopping-app.git

              # Install required tools
              sudo apt update
              sudo apt install -y git curl psmisc

              # Install Node.js (v18)
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt install -y nodejs

              # Navigate to home and remove old app folder
              cd /home/$EC2_USER
              rm -rf $APP_DIR

              # Clone repo
              git clone $REPO_URL
              cd $APP_DIR

              # Install dependencies and build
              npm install
              npm run build

              # Install serve if missing
              if ! command -v serve > /dev/null; then
                sudo npm install -g serve
              fi

              # Kill any existing app on port 3000
              fuser -k 3000/tcp || true

              # Serve build directory
              nohup serve -s build -l tcp://0.0.0.0:3000 > /tmp/serve.log 2>&1 &
            EOF

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy






