version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:18.17.0
    environment:
      APP_DIR: react-app
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "SHA256:nvBo8bI+QsWnA9X51EFwxDMrbLDhVU1qtSZGf7Cd9aE"

      - run:
          name: Copy project to EC2
          command: |
            rsync -az -e "ssh -o StrictHostKeyChecking=no" ./ $EC2_USER@$EC2_HOST:/home/$EC2_USER/$APP_DIR

      - run:
          name: Build and serve React app on EC2
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST \<< EOF
              cd /home/$EC2_USER/$APP_DIR

              # Install dependencies and build
              npm install
              npm run build

              # Install serve globally if not already installed
              if ! command -v serve > /dev/null; then
                npm install -g serve
              fi

              # Kill old process running on port 3000
              fuser -k 3000/tcp || true

              # Start serve in background
              nohup serve -s build -l 3000 > serve.log 2>&1 &
            EOF

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy


workflows:
  version: 2
  deploy_workflow:
    jobs:
      - build_and_deploy
