version: 2.1

jobs:
  deploy:
    machine: true
    environment:
      APP_DIR: online-shopping-app
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "SHA256:nvBo8bI+QsWnA9X51EFwxDMrbLDhVU1qtSZGf7Cd9aE"

      - run:
          name: SSH into EC2 and deploy React app
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST \<< 'EOF'
              # Set up variables
              REPO_URL=https://github.com/Prasannaramesh13/online-shopping-app.git
              APP_DIR=online-shopping-app
              USER_HOME=/home/$USER

              # Change to user's home directory
              cd $USER_HOME

              # Install required tools
              sudo apt update
              sudo apt install -y git curl psmisc

              # Install Node.js (v18)
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt install -y nodejs

              # Remove old app if exists
              rm -rf $APP_DIR

              # Clone the app (into your own home dir)
              git clone $REPO_URL
              cd $APP_DIR

              # Install dependencies and build
              npm install
              npm run build

              # Install 'serve' globally if missing
              if ! command -v serve > /dev/null; then
                sudo npm install -g serve
              fi

              # Kill existing app if needed
              fuser -k 3000/tcp || true

              # Serve the app
              nohup serve -s build -l tcp://0.0.0.0:3000 > /tmp/serve.log 2>&1 &
            EOF

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
