version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:18.17.0
    environment:
      APP_DIR: online-shopping-app
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "SHA256:nvBo8bI+QsWnA9X51EFwxDMrbLDhVU1qtSZGf7Cd9aE"

      - run:
          name: SSH into EC2 and deploy React app
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST \<< 'EOF'
              # Setup
              sudo apt update
              sudo apt install -y git psmisc curl

              cd /home/$EC2_USER

              # Clone or pull the repo
              if [ -d "$APP_DIR/.git" ]; then
                cd $APP_DIR && git pull
              else
                git clone https://github.com/Prasannaramesh13/online-shopping-app.git $APP_DIR
                cd $APP_DIR
              fi

              # Install Node.js
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt install -y nodejs

              # Install dependencies & build
              cd /home/$USER/$APP_DIR
              npm install
              npm run build

              # Install serve globally with sudo
              if ! command -v serve > /dev/null; then
                sudo npm install -g serve
              fi

              # Kill any process on port 3000
              fuser -k 3000/tcp || true

              # Serve build (output to /tmp to avoid permission issues)
              nohup serve -s build -l tcp://0.0.0.0:3000 > /tmp/serve.log 2>&1 &
            EOF

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy


