version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:18.17.0
    environment:
      APP_DIR: react-app
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "SHA256:nvBo8bI+QsWnA9X51EFwxDMrbLDhVU1qtSZGf7Cd9aE"

      - run:
          name: Build and serve React app on EC2
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST \<< 'EOF'
              sudo apt update
              sudo apt install -y git psmisc curl

              cd /home/$EC2_USER
              if [ -d "$APP_DIR/.git" ]; then
                cd $APP_DIR && git pull
              else
                git clone https://github.com/Prasannaramesh13/online-shopping-app.git $APP_DIR
                cd $APP_DIR
              fi

              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt install -y nodejs

              npm install
              npm run build

              if ! command -v serve > /dev/null; then
                npm install -g serve
              fi

              fuser -k 3000/tcp || true

              nohup serve -s build -l tcp://0.0.0.0:3000 > /home/$EC2_USER/serve.log 2>&1 &
            EOF

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy

